# setw -g cursor-colour none
setw -g cursor-style default
setw -g menu-style default
setw -g menu-selected-style bg=yellow,fg=black
setw -g menu-border-style default
setw -g menu-border-lines single
setw -g aggressive-resize off
setw -g allow-passthrough off
setw -g allow-rename off
setw -g allow-set-title on
setw -g alternate-screen on
setw -g automatic-rename on
setw -g automatic-rename-format "#{?pane_in_mode,[tmux],#{pane_current_command}}#{?pane_dead,[dead],}"
setw -g clock-mode-colour blue
setw -g clock-mode-style 24
setw -g copy-mode-match-style bg=cyan,fg=black
setw -g copy-mode-current-match-style bg=magenta,fg=black
setw -g copy-mode-mark-style bg=red,fg=black
setw -gu fill-character ''
setw -g main-pane-height 24
setw -g main-pane-width 80
setw -g mode-keys vi
setw -g mode-style bg=yellow,fg=black
setw -g monitor-activity off
setw -g monitor-bell on
setw -g monitor-silence 0
setw -g other-pane-height 0
setw -g other-pane-width 0
setw -g pane-active-border-style "#{?pane_in_mode,fg=yellow,#{?synchronize-panes,fg=red,fg=green}}"
setw -g pane-base-index 0
setw -g pane-border-format "#{?pane_active,#[reverse],}#{pane_index}#[default] \"#{pane_title}\""
setw -g pane-border-indicators colour
setw -g pane-border-lines single
setw -g pane-border-status off
setw -g pane-border-style default
setw -gu pane-colours
setw -g popup-style default
setw -g popup-border-style default
setw -g popup-border-lines single
setw -g remain-on-exit off
setw -g remain-on-exit-format "Pane is dead (#{?#{!=:#{pane_dead_status},},status #{pane_dead_status},}#{?#{!=:#{pane_dead_signal},},signal #{pane_dead_signal},}, #{t:pane_dead_time})"
setw -g scroll-on-clear on
setw -g synchronize-panes off
setw -g window-active-style default
setw -g window-size latest
setw -g window-style default
setw -g window-status-activity-style reverse
setw -g window-status-bell-style reverse
setw -g window-status-current-format "#I:#W#{?window_flags,#{window_flags}, }"
setw -g window-status-current-style default
setw -g window-status-format "#I:#W#{?window_flags,#{window_flags}, }"
setw -g window-status-last-style default
setw -g window-status-separator " "
setw -g window-status-style default
setw -g wrap-search on
setw -g xterm-keys on
