# Basic configuration
set -g @powerkit_plugins "datetime,battery,cpu,memory,git,hostname"
# set -g @powerkit_theme "catppuccin"
# set -g @powerkit_theme_variant "mocha"
set -g @powerkit_theme "Nord"
set -g @powerkit_theme_variant "dark"

set -g @powerkit_options_key "C-e"          # View all options
set -g @powerkit_keybindings_key "C-y"      # View keybindings
set -g @powerkit_theme_selector_key "C-r"   # Theme selector
set -g @powerkit_cache_clear_key "C-d"      # Clear cache

# set -g @powerkit_separator_style "normal"
# set -g @powerkit_separator_style "rounded"
# set -g @powerkit_separator_style "flame"
# set -g @powerkit_separator_style "honeycomb"
# set -g @powerkit_edge_separator_style "flame"
# set -g @powerkit_initial_separator_style "rounded"
# set -g @powerkit_separator_style "pixel"
# set -g @powerkit_separator_style "none"
set -g @powerkit_elements_spacing "both"  # false, true, both, windows, plugins
set -g @powerkit_separator_style "normal"

#   "normal"    - Solid powerline arrows ()
#   "rounded"   - Rounded powerline ()
#   "slant"     - Slanted diagonal ()
#   "slantup"   - Upward slant ()
#   "trapezoid" - Trapezoid shape ()
#   "flame"     - Flame/fire style ()
#   "pixel"     - Pixelated blocks ()
#   "honeycomb" - Hexagonal pattern ()
#   "none"      - No separators

