source -F "/Users/mahlstrom/.config/tmux/themebox/default.conf"
source -F "/Users/mahlstrom/.config/tmux/themebox/defaultw.conf"
run "/Users/mahlstrom/.config/tmux/themebox/reset.sh"

source -F "/Users/mahlstrom/.config/tmux/tmux_sesh.conf"
run-shell /Users/mahlstrom/.config/tmux/sensible.tmux
source -F "/Users/mahlstrom/.config/tmux/tmux.keyboard.conf"
source -F "/Users/mahlstrom/.config/tmux/tmux.settings.conf"

#################################################
# Status bar
#################################################
set -g status-position top
setw -g clock-mode-style  24
set -g status-left-length 40

# source -F "#{d:current_file}/demo2/tsb.tmux"
# source -F "#{d:current_file}/old_catppuccin.tmux"
# source -F "/Users/mahlstrom/.config/tmux/tmux.theme.my.conf"
source -F "/Users/mahlstrom/.config/tmux/tmux.theme.catppuccin2.conf"
# source -F "/Users/mahlstrom/.config/tmux/tmux.theme.2k.conf"

#################################################
# Status plugins
#################################################

set -g @plugin 'tmux-plugins/tmux-cpu'

#################################################
# Other plugins
#################################################
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-bind 'o'


# tmux plugin manager
set -g @plugin 'tmux-plugins/tpm'
run '~/.config/tmux/plugins/tpm/tpm'
