set -g @theme_plugins 'music,datetime,weather,battery'
set -g @theme_transparent_status_bar 'true'

# set -g @theme_variation 'storm'
# set -gu @theme_left_separator ''
# set -gu @theme_right_separator ''
# set -g @theme_transparent_status_bar 'false'
set -gu @theme_transparent_left_separator_inverse ''
set -gu @theme_transparent_right_separator_inverse ''
set -g @theme_plugin_homebrew_additional_options ' '
set -g @theme_plugin_weather_location 'Uppsala, Sweden'
set -g @theme_plugin_datetime_format '%Y-%m-%d  %H:%M'
set -g @theme_plugin_homebrew_accent_color 'purple'
run /Users/mahlstrom/.config/tmux/themes/mahlstrom/mytokyo/src/state.sh
run /Users/mahlstrom/.config/tmux/themes/mahlstrom/mytokyo/mytokyo-night.tmux
