# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
# set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_status_style "slanted"

set -g @catppuccin_status_background "#242638"
set -g @catppuccin_window_current_text " #{b:pane_current_path}"
set -g @catppuccin_window_text " #{b:pane_current_path}"
set -g @plugin 'xamut/tmux-weather'
# Load catppuccin
# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# set -g @plugin 'catppuccin/tmux'
# set -g @plugin 'tmux-plugins/tmux-battery'
# set -g @plugin 'xamut/tmux-weather'
# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_weather}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set-window-option -g status-position top
