set  -g default-terminal "tmux-256color"
set-option -a terminal-features 'xterm-256color:RGB'

set  -g base-index      1
setw -g pane-base-index 1
set -g renumber-windows on   # renumber all windows when any window is closed

set  -g mouse             on
setw -g aggressive-resize off
set  -s escape-time       10
set  -g history-limit     25000
set -as terminal-overrides ",$TERM:Tc"

set -g set-clipboard on      # use system clipboard

set -g detach-on-destroy off  # don't exit from tmux when closing a session

# WizTerm needs this to work
set -g allow-passthrough on

set -g status-interval 3     # update the status bar every 3 seconds

set -g default-shell /bin/zsh
# set -g default-command /bin/zsh

