# mkdir -p ~/.config/tmux/plugins/catppuccin
# git clone -b v2.1.2 https://github.com/catppuccin/tmux.git ~/.config/tmux/plugins/catppuccin/tmux

set -g @catppuccin_flavor 'mocha' # or frappe, macchiato, mocha, latte

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux