# rebind main key: C-a
unbind C-b
set -g prefix C-Space
# bind -N "Send the prefix key through to the application" \
#  a send-prefix
# bind C-a last-window

set -g status-keys vi
set -g mode-keys   vi

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
# vi for copy mode
# setw -g mode-keys vi
bind-key C-e copy-mode

# set -g status-bg default
# set -g status-interval 1
# set -g status-left ""

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection

bind C-f display-popup -E 'sesh connect "$(sesh list -i -d|gum filter --limit 1 --no-strip-ansi --placeholder '\''Pick a sesh'\'' --prompt='\''⚡'\'')"'
bind C-t display-popup -E '~/.config/tmux/themebox/themebox.tmux "$(~/.config/tmux/themebox/themebox.tmux --list|sort|gum filter --limit 1 --no-strip-ansi --placeholder '\''Pick a theme'\'' --prompt='\''⚡'\'')"'

bind C-x run "#{d:config_files}/themes/mahlstrom/mytokyo/mytokyo-night.tmux"
bind-key c new-window -c "#{pane_current_path}"
bind-key C-h split-window -h -c "#{pane_current_path}"
bind-key C-v split-window -v -c "#{pane_current_path}"

# Tab navigation
bind-key -n C-Tab next-window
bind-key -n C-S-Tab previous-window

# reload configuration
bind-key -r r source-file ~/.config/tmux/tmux.conf
bind-key -r C-r source-file ~/.config/tmux/tmux.conf

