if [[ -z "$ZSHENV_LOADED" ]]; then
    # Environment variables
  export ZSHENV_LOADED=1
  export CLICLOLOR="1"
  export EDITOR="nvim"
  export NVIM_APPNAME="nvim_files/mahlstrom/nvim-newsbs/"
  export NVIM_APPNAME2="nvim_files/mahlstrom/nvim/"
  export PAGER="less"
  
  # Paths
  typeset -U path

  path=(
    /opt/homebrew/bin
    /opt/homebrew/sbin
    $HOME/.config/composer/vendor/bin
    $HOME/github.com/mahlstrom/php-bin/bin
    /opt/homebrew/opt/mysql-client/bin
    /Users/mahlstrom/github.com/mahlstrom/argbash
    /Applications/PhpStorm.app/Contents/MacOS
    /usr/local/bin
    /usr/local/sbin
    # $path  # keep remaining existing system paths at the end
  )
  
  export HOMEBREW_BUNDLE_FILE="$HOME/.config/homebrew/Brewfile_$MACHINE"
  for file in $HOME/.config/*/.zshenv(N); do
    if [[ -f $file ]]; then
      source "$file"
    fi
  done
fi
