# Interactive shell-specific configurations

# Zsh options
setopt HIST_FCNTL_LOCK
unsetopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_SPACE
setopt SHARE_HISTORY

# History settings
HISTSIZE="10000"
SAVEHIST="10000"
HISTFILE="$HOME/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

# Initialize completion system
autoload -Uz compinit
compinit

# Plugins
source $HOME/.config/zsh/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_STRATEGY=(history)

bindkey -e

# Load tool-specific configs
for dir in $HOME/.config/*(/); do
  local tool_name=$(basename "$dir")
  local loadable=0

  if [[ "$tool_name" == "zsh" || "$tool_name" == "bash" || "$tool_name" == "common" ]] || (( $+commands[$tool_name] )); then
    loadable=1
  elif [[ -f "$dir/.commands" ]]; then
    while IFS= read -r cmd; do
      if (( $+commands[$cmd] )); then
        loadable=1
        break
      fi
    done < "$dir/.commands"
  fi

  if (( loadable  )); then
    [[ -f "$dir/.zshrc" ]] && source "$dir/.zshrc"
    [[ -f "$dir/alias.sh" ]] && source "$dir/alias.sh"
    [[ -f "$dir/init.sh" ]] && source "$dir/init.sh"
  fi
done

for file in $HOME/github.com/mahlstrom/*/bin/.zshrc(N); do
  if [[ -f $file ]]; then
    source "$file"
  fi
done


# bun completions
[ -s "/Users/mahlstrom/.bun/_bun" ] && source "/Users/mahlstrom/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
